### ISSUE TITLE
Message Bubble Not Showing Text

### ISSUE THREAD

**Issue by Chibson** [SerenaKit/Antoine#2] opened 2023-03-09 16:27 UTC
Whenever I select a process from the stream list, the message bubble doesn't show text; it's blank as you can see from the attached photo. 
![IMG_4720](https://user-images.githubusercontent.com/41264900/224088115-9d1beebb-158d-4893-8ae8-e9e64f012ef6.png)

**Comment by NSAntoine** [comment] 2023-03-09 16:30
Does this happen with *all* logs?

**Comment by Chibson** [comment] 2023-03-09 16:54
> Does this happen with _all_ logs?

Yes it does.

**Comment by Chibson** [comment] 2023-03-09 16:56
On iOS 13.7 if that makes a difference

**Comment by NSAntoine** [comment] 2023-03-09 19:58
Here is a debug build that will try to pinpoint what exactly went wrong, tap a log, the message section may look ugly (it will), but that's on purpose to see if the issue is colors: https://cdn.discordapp.com/attachments/1037027477207400503/1083478546938339468/Antoine.deb
@Chibson Let me know if it works

**Comment by Chibson** [comment] 2023-03-10 03:21
> Here is a debug build that will try to pinpoint what exactly went wrong, tap a log, the message section may look ugly (it will), but that's on purpose to see if the issue is colors: https://cdn.discordapp.com/attachments/1037027477207400503/1083478546938339468/Antoine.deb @Chibson Let me know if it works

Same issue still, looks identical to my screenshot. I installed it through filza, that's a valid way to install a .deb file right?

**Comment by NSAntoine** [comment] 2023-03-10 07:41
> > Here is a debug build that will try to pinpoint what exactly went wrong, tap a log, the message section may look ugly (it will), but that's on purpose to see if the issue is colors: https://cdn.discordapp.com/attachments/1037027477207400503/1083478546938339468/Antoine.deb @Chibson Let me know if it works
> 
> Same issue still, looks identical to my screenshot. I installed it through filza, that's a valid way to install a .deb file right?

But it shouldn’t look the same at all, take a screenshot please (also yes filza is a valid way)

**Comment by Chibson** [comment] 2023-03-10 19:35
![IMG_4726](https://user-images.githubusercontent.com/41264900/224410811-b35c765f-beeb-4561-ac08-23ce768316c2.png)
![IMG_4727](https://user-images.githubusercontent.com/41264900/224410813-b089a5b3-53d9-45c2-ad90-ff5bc2dc6038.png)

**Comment by NSAntoine** [comment] 2023-03-13 04:21
Bizarre, don’t really know the root cause and I’ve been trying to find it for an hour and a half now..

**Comment by Chibson** [comment] 2023-03-13 21:50
> Bizarre, don’t really know the root cause and I’ve been trying to find it for an hour and a half now..

Don't worry about it too much. I just updated my phone to iOS 16.3.1 (jailbroken on palera1n) and the messages are showing up now.

**Comment by NSAntoine** [comment] 2023-05-12 10:44
Should be fixed now, I'm sorry I wasn't able to find it earlier

**Closed as completed by NSAntoine** 2023-05-12 10:44 UTC
